language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'ppa:jonathonf/python-3.6'
          packages:
            - curl
            - xorg-dev
            - libglfw3-dev
            - swig3.0
            - python3.6-dev
            - gcc-8
            - g++-8
      script:
        - echo "RUNNING XENIAL BUILD"
        - mkdir build
        - mkdir install
        - cd build
        - echo "GETTING THE BEST CMAKE VERSION..."
        - wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.sh
        - bash cmake-3.13.3-Linux-x86_64.sh --skip-license
        - echo "GETTING THE VULKANS..."
        - wget https://sdk.lunarg.com/sdk/download/1.1.97.0/linux/vulkansdk-linux-x86_64-1.1.97.0.tar.gz
        - tar -xzf vulkansdk-linux-x86_64-1.1.97.0.tar.gz
        - ./bin/cmake -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-8 -DVulkan_INCLUDE_DIR:PATH=$(pwd)/1.1.97.0/x86_64/include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/1.1.97.0/x86_64/lib/libvulkan.so ../
        - cmake --build .
        - cmake --build . --target install
    - os: osx
      osx_image: xcode10.1
      script:
        - brew upgrade cmake
        - brew install swig
        - mkdir build
        - mkdir install
        - cd build
        - curl https://sdk.lunarg.com/sdk/download/1.1.97.0/mac/vulkansdk-macos-1.1.97.0.tar.gz -o vulkan.tar.gz
        - tar -xzf vulkan.tar.gz
        - cmake -DVulkan_INCLUDE_DIR:PATH=$(pwd)/vulkansdk-macos-1.1.97.0/macos/include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/vulkansdk-macos-1.1.97.0/macos/lib/libvulkan.dylib ../ ../
        - cmake --build .
        - cmake --build . --target install
    - os: windows
      script: 
        - choco install cmake
        - choco upgrade cmake
        - choco install python3
        - choco upgrade python3
        - choco install swig
        - choco upgrade swig
        - wget https://sdk.lunarg.com/sdk/download/1.1.97.0/windows/VulkanSDK-1.1.97.0-Installer.exe
        - ./VulkanSDK-1.1.97.0-Installer.exe /S
        - mkdir build
        - mkdir install
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ../
        - cmake --build .
        - cmake --build . --target install


