language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'ppa:jonathonf/python-3.6'
            - sourceline: 'deb https://packages.lunarg.com/vulkan/1.1.97 xenial main'
              key_url: 'http://packages.lunarg.com/lunarg-signing-key-pub.asc'
          packages:
            - curl
            - xorg-dev
            - libglfw3-dev
            - swig3.0
            - python3.6-dev
            - gcc-8
            - g++-8
            - lunarg-vulkan-sdk
      script:
        - mkdir build
        - mkdir install
        - cd build
        - wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.sh
        - bash cmake-3.13.3-Linux-x86_64.sh --skip-license
        - ./bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-8 ../
        - cmake --build . --target install --config Release
    - os: osx
      osx_image: xcode10.1
      script:
        - mkdir build
        - mkdir install
        - brew upgrade cmake wget
        - brew install swig
        - cd build
        - wget https://sourceforge.net/projects/vulkantarball/files/vulkansdk-macos-1.1.97.0.tar.gz/download
        - mv download vulkan.tar.gz
        - tar -xzf vulkan.tar.gz
        - export PATH=$PATH:"$(pwd)/vulkansdk-macos-1.1.97.0/macOS/bin"
        - export VULKAN_SDK="$(pwd)/vulkansdk-macos-1.1.97.0/macOS/"
        - cmake -DCMAKE_BUILD_TYPE=Release -DVulkan_INCLUDE_DIR:PATH=$(pwd)/vulkansdk-macos-1.1.97.0/macOS/include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/vulkansdk-macos-1.1.97.0/macOS/lib/libvulkan.dylib ../ ../
        - cmake --build . --target install --config Release
    - os: windows
      script: 
        - mkdir build
        - mkdir install
        - choco install cmake python3 swig
        - wget -q https://sourceforge.net/projects/vulkantarball/files/vulkansdk-windows-1.1.97.0.tar.gz/download
        - mv download vulkan.tar.gz
        - tar -xzf vulkan.tar.gz
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DVULKAN_SDK:PATH=$(pwd)/../1.1.97.0/ -DVulkan_INCLUDE_DIR:PATH=$(pwd)/../1.1.97.0/Include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/../1.1.97.0/Lib/vulkan-1.lib ../
        - cmake --build . --target install --config Release


