language: cpp

dist: xenial

addons:
  apt:
    packages:
      - curl
      - xorg-dev
      - libglfw3-dev
      - swig3.0
      - python3-dev
      - gcc-8

script:
  - mkdir build
  - mkdir install
  - cd build
  - echo "GETTING THE BEST CMAKE VERSION..."
  - wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.sh
  - bash cmake-3.13.3-Linux-x86_64.sh --skip-license
  - echo "GETTING THE VULKANS..."
  - wget https://sdk.lunarg.com/sdk/download/1.1.97.0/linux/vulkansdk-linux-x86_64-1.1.97.0.tar.gz
  - tar -xzf vulkansdk-linux-x86_64-1.1.97.0.tar.gz
  - ./bin/cmake -DVulkan_INCLUDE_DIR:PATH=$(pwd)/1.1.97.0/x86_64/include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/1.1.97.0/x86_64/lib/libvulkan.so ../
  - echo "STARTING BUILD..."
  - make
  - echo "DONE BUILDING!"
  - make install
