language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'ppa:jonathonf/python-3.6'
            - sourceline: 'deb https://packages.lunarg.com/vulkan/1.1.97 xenial main'
              key_url: 'http://packages.lunarg.com/lunarg-signing-key-pub.asc'
          packages:
            - curl
            - xorg-dev
            - libglfw3-dev
            - swig3.0
            - python3.6-dev
            - gcc-8
            - g++-8
            - lunarg-vulkan-sdk
      script:
        - echo "RUNNING XENIAL BUILD"
        - mkdir build
        - mkdir install
        - cd build
        - echo "GETTING THE BEST CMAKE VERSION..."
        - wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.sh
        - bash cmake-3.13.3-Linux-x86_64.sh --skip-license
        - ./bin/cmake -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-8 ../
        - cmake --build .
        - cmake --build . --target install
    - os: osx
      osx_image: xcode10.1
      script:
        - brew upgrade cmake
        - brew install swig
        - brew install wget
        - brew upgrade wget
        - mkdir build
        - mkdir install
        - cd build
        - wget https://sdk.lunarg.com/sdk/download/1.1.97.0/mac/vulkansdk-macos-1.1.97.0.tar.gz?u=
        - tar -xzf vulkansdk-macos-1.1.97.0.tar.gz
        - cmake -DVulkan_INCLUDE_DIR:PATH=$(pwd)/vulkansdk-macos-1.1.97.0/macos/include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/vulkansdk-macos-1.1.97.0/macos/lib/libvulkan.dylib ../ ../
        - cmake --build .
        - cmake --build . --target install
    - os: windows
      script: 
        - choco install cmake
        - choco upgrade cmake
        - choco install python3
        - choco upgrade python3
        - choco install swig
        - choco upgrade swig
        - wget -q https://sourceforge.net/projects/vulkantarball/files/vulkansdk-windows-1.1.97.0.tar.gz/download
        - mv download vulkan.tar.gz
        - tar -xzvf vulkan.tar.gz
        - mkdir build
        - mkdir install
        - set "project_dir=%cd%"
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DVulkan_INCLUDE_DIR:PATH=%project_dir%/1.1.97.0/Include/ -DVulkan_LIBRARY:FILEPATH=%project_dir%/1.1.97.0/Lib/vulkan-1.lib ../
        - cmake --build .
        - cmake --build . --target install


