language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'ppa:jonathonf/python-3.6'
          packages:
            - curl
            - xorg-dev
            - libglfw3-dev
            - swig3.0
            - python3.6-dev
            - gcc-8
            - g++-8
      script:
        - echo "RUNNING XENIAL BUILD"
        - mkdir build
        - mkdir install
        - cd build
        - echo "GETTING THE BEST CMAKE VERSION..."
        - wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.sh
        - bash cmake-3.13.3-Linux-x86_64.sh --skip-license
        - echo "GETTING THE VULKANS..."
        - wget https://sdk.lunarg.com/sdk/download/1.1.97.0/linux/vulkansdk-linux-x86_64-1.1.97.0.tar.gz
        - tar -xzf vulkansdk-linux-x86_64-1.1.97.0.tar.gz
        - ./bin/cmake -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-8 -DVulkan_INCLUDE_DIR:PATH=$(pwd)/1.1.97.0/x86_64/include/ -DVulkan_LIBRARY:FILEPATH=$(pwd)/1.1.97.0/x86_64/lib/libvulkan.so ../
        - echo "STARTING BUILD..."
        - make
        - echo "DONE BUILDING!"
        - make install
    - os: osx
      osx_image: xcode10.1
      script:
        - brew install cmake
        - brew install python
        - brew install wget
        - mkdir build
        - mkdir install
        - cd build
        - cmake ../
    - os: windows
      script: 
        - choco install cmake
        - choco upgrade cmake
        - choco install wget
        - choco upgrade wget
        - choco install python3
        - choco upgrade python3
        - makedir build
        - makedir install
        - cd build
        - cmake ../


